#!/usr/bin/env node
/**
 * Static site generator.
 *
 * Content lives as files in this repository, never in a CMS — IA §19 (Q4):
 * an institution planning in decades cannot have its record trapped in a
 * vendor's database. Assembling partials + page content into complete HTML
 * documents is the whole of the build.
 */
import { readFileSync, writeFileSync, mkdirSync, cpSync, rmSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'src');
const OUT = join(ROOT, 'dist');

const read = (p) => readFileSync(join(SRC, p), 'utf8');
const manifest = JSON.parse(read('pages/manifest.json'));
/* The Study is GENERATED from the academic engine rather than authored as
   markup, so the interface cannot drift from the model it presents. */
const { renderStudyHome, renderReadingRoom } = await import('../src/study-preview.mjs');

/* Tokens are replaced with a function so `$&`-style sequences inside
   content (e.g. a `$` in copy) can never corrupt the output. */
const fill = (tpl, vars) =>
  tpl.replace(/\{\{(\w+)\}\}/g, (m, k) => (k in vars ? vars[k] : m));

/* Illumination is generated by scripts/make-art.mjs from real geometric
   construction and inlined here, so a plate costs no request and inherits
   currentColor from the band it sits in. `{{ART:shamsa}}` in any page or
   partial becomes the SVG. Generated art is inlined, never hand-edited: the
   construction is the source, the SVG is output. */
const ART = {};
for (const n of ['shamsa', 'girih', 'unwan', 'arch']) {
  const f = join(SRC, 'assets', `${n}.svg`);
  if (existsSync(f)) ART[n] = readFileSync(f, 'utf8').replace(/\n\s*/g, '');
}
const inlineArt = (html) =>
  html.replace(/\{\{ART:(\w+)\}\}/g, (m, k) => ART[k] || '');

/* Resolves `<name>.<lang>.html` when it exists, else `<name>.html`.
   Adopted from the WEC-LC precedent (WEC §2.2): adding a partial needs no
   build change, and a language without its own copy degrades to the base
   partial instead of throwing. */
const partialFor = (name, lang) => {
  const localised = join(SRC, 'partials', `${name}.${lang}.html`);
  return read(existsSync(localised) ? `partials/${name}.${lang}.html` : `partials/${name}.html`);
};

const BUILT = new Date().toISOString().slice(0, 10);

function render(page) {
  const ar = page.lang === 'ar';
  const dir = ar ? 'rtl' : 'ltr';
  const content = page.layout === 'study' ? renderStudyHome(page.lang || 'en')
    : page.layout === 'room' ? renderReadingRoom(page.lang || 'en')
    : read(`pages/${page.contentFile}`);
  const canonical = page.output === 'index.html' ? '/' : '/' + page.output.replace(/index\.html$/, '');
  /* hreflang must label each URL by ITS OWN language, not by the page being
     rendered. Deriving `en` from the canonical is only correct on English
     pages — on Arabic pages it inverts the pair. Caught in production. */
  const head = fill(partialFor('head', page.lang || 'en'), {
    TITLE: page.title,
    DESCRIPTION: page.description,
    LANG: page.lang || 'en',
    CANONICAL: canonical,
    HREF_EN: ar ? page.altHref : canonical,
    HREF_AR: ar ? canonical : page.altHref,
    NOINDEX: page.noindex ? '<meta name="robots" content="noindex">' : '',
    OG_LOCALE: ar ? 'ar_AR' : 'en_GB',
    OG_TITLE: page.title,
    OG_SITE: ar
      ? 'كلية المدينة العالمية للدراسات العربية والإسلامية'
      : "Al-Madeenah International College for Arabic &amp; Islamic Studies",
  });

  let body;
  if (page.layout === 'portal' || page.layout === 'study' || page.layout === 'room') {
    body = content; // these carry their own shell
  } else {
    const lang = page.lang || 'en';
    const topbar = fill(partialFor('topbar', lang), { ALT_HREF: page.altHref });
    const header = fill(partialFor('header', lang), { ALT_HREF: page.altHref });
    const footer = fill(partialFor('footer', lang), { BUILT });
    body = `${topbar}\n${header}\n<main id="main">\n${content}\n</main>\n${footer}`;
  }

  return inlineArt(`<!doctype html>
<html lang="${page.lang || 'en'}" dir="${dir}">
<head>
${head}
</head>
<body>
${/* The Study carries its own skip link and its own, more specific preview
      notice. Emitting the site-wide pair as well produced two banners stacked
      on top of each other and two skip links in the tab order — found by
      screenshotting the page, not by reading the template. */
  page.layout === 'study' || page.layout === 'room' ? '' :
`<a class="skip" href="#main">${ar ? 'تخطَّ إلى المحتوى' : 'Skip to content'}</a>
<div class="previewbar"><div class="wrap">${
    ar
      ? '<strong>معاينة تصميمية</strong> — هذه معاينة قيد التطوير، وليست موقعًا رسميًا. المحتوى العربي بانتظار مراجعة متحدّث أصلي.'
      : '<strong>Design preview</strong> — a work in progress, not a live institutional site. Arabic copy awaits native-speaker review (EB §11.8).'
  }</div></div>`}
${body}
<div class="s-overlay" id="search" hidden>
  <div class="s-panel" role="dialog" aria-modal="true" aria-label="${ar ? 'بحث في الموقع' : 'Search this site'}">
    <div class="s-bar">
      <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><circle cx="11" cy="11" r="7" fill="none" stroke="currentColor" stroke-width="1.5"/><path d="M16.5 16.5L21 21" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg>
      <input type="search" data-s-input autocomplete="off" spellcheck="false"
        placeholder="${ar ? 'ابحث في الكلية…' : 'Search the College…'}"
        aria-label="${ar ? 'كلمة البحث' : 'Search terms'}">
      <button type="button" data-s-close class="s-esc" aria-label="${ar ? 'إغلاق' : 'Close'}">esc</button>
    </div>
    <div class="s-out" data-s-out></div>
    <p class="s-hint">${ar ? 'اضغط ⌘K أو / للبحث' : 'Press ⌘K or / to search'}</p>
  </div>
</div>
<script src="/site.js" defer></script>
</body>
</html>
`);
}

/* ---------------- build ---------------- */
if (existsSync(OUT)) rmSync(OUT, { recursive: true });
mkdirSync(OUT, { recursive: true });

let n = 0;
for (const page of manifest.pages) {
  const dest = join(OUT, page.output);
  mkdirSync(dirname(dest), { recursive: true });
  writeFileSync(dest, render(page), 'utf8');
  n++;
}

/* CSS: fonts.css is generated (self-hosted @font-face), brand.css is authored.
   Concatenated so a page makes one stylesheet request — EB §24. */
writeFileSync(join(OUT, 'brand.css'), read('fonts.css') + '\n' + read('brand.css'), 'utf8');
cpSync(join(SRC, 'site.js'), join(OUT, 'site.js'));
cpSync(join(ROOT, 'assets'), join(OUT, 'assets'), { recursive: true });

/* robots + sitemap. The verification host is noindex by policy (IA §4) and
   is not part of this deployment. */
const urls = manifest.pages
  .filter((p) => !p.noindex)
  .map((p) => `  <url><loc>https://almadinah.college/${p.output.replace(/index\.html$/, '')}</loc></url>`)
  .join('\n');
writeFileSync(
  join(OUT, 'sitemap.xml'),
  `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`
);
/* ---------------- search index (FR-1) ----------------
   Built from the rendered pages, not from the source: what a reader can search
   is exactly what a reader can see. One index per language, because a search
   that returns Arabic results to an English reader is a broken search, not a
   bilingual one. */
const ent = (t) => t
  .replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
  .replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&nbsp;/g, ' ');
const strip = (h) => h
  .replace(/<script[\s\S]*?<\/script>/g, ' ')
  .replace(/<style[\s\S]*?<\/style>/g, ' ')
  .replace(/<svg[\s\S]*?<\/svg>/g, ' ')
  .replace(/<(header|footer|nav)[\s\S]*?<\/\1>/g, ' ')
  .replace(/<[^>]+>/g, ' ')
  /* Decode the entities that carry a character before discarding the rest:
     stripping &amp; to a space indexed the College's own name as
     "Arabic  Islamic Studies". */
  .replace(/&amp;/g, '&').replace(/&nbsp;/g, ' ')
  .replace(/&#(\d+);/g, (_, d) => String.fromCharCode(+d))
  .replace(/&[a-z]+;|&#\d+;/g, ' ')
  .replace(/\s+/g, ' ')
  .trim();

for (const lang of ['en', 'ar']) {
  const idx = manifest.pages
    .filter((pg) => (pg.lang || 'en') === lang && !pg.noindex && pg.output !== '404.html')
    .map((pg) => {
      const file = join(OUT, pg.output);
      const html = readFileSync(file, 'utf8');
      const url = '/' + pg.output.replace(/index\.html$/, '');
      const main = (html.match(/<main id="main">([\s\S]*?)<\/main>/) || [, ''])[1];
      return {
        u: url,
        /* Titles and descriptions are read out of the RENDERED page, so they
           arrive HTML-escaped. The index is consumed as text, so it must be
           decoded — otherwise the search box offers the reader "Arabic &amp;
           Islamic Studies". */
        t: ent((html.match(/<title>([^<]*)<\/title>/) || [, ''])[1].replace(/ — .*$/, '')),
        d: ent((html.match(/name="description" content="([^"]*)"/) || [, ''])[1]),
        /* Capped: an index a phone must download before it can search is not a
           feature. 1,800 characters covers every heading and lead on a page. */
        b: strip(main).slice(0, 1800),
      };
    });
  writeFileSync(join(OUT, `search-${lang}.json`), JSON.stringify(idx), 'utf8');
}

/* FR-2 — the worker is versioned by build date so a deploy invalidates the
   old cache. Written from src/ with the token filled, not copied. */
writeFileSync(join(OUT, 'sw.js'), fill(read('sw.js'), { BUILT }), 'utf8');
writeFileSync(join(OUT, 'manifest.webmanifest'), JSON.stringify({
  name: "Al-Madeenah International College for Arabic &amp; Islamic Studies",
  short_name: 'Al-Madeenah',
  start_url: '/',
  scope: '/',
  display: 'standalone',
  background_color: '#F6F0E1',
  theme_color: '#1A3280',
  lang: 'en',
  dir: 'ltr',
  description: "Arabic language, Qur'anic memorisation and the Islamic sciences, taught to a published standard.",
  icons: [
    { src: '/assets/favicon.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'any maskable' },
  ],
}, null, 2), 'utf8');

writeFileSync(join(OUT, 'robots.txt'), 'User-agent: *\nAllow: /\nSitemap: https://almadinah.college/sitemap.xml\n');
writeFileSync(
  join(OUT, '_headers'),
  `/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  X-Frame-Options: DENY\n  Permissions-Policy: geolocation=(), microphone=(), camera=()\n/assets/fonts/*\n  Cache-Control: public, max-age=31536000, immutable\n`
);

console.log(`built ${n} pages → dist/`);
